In [30]:
import numpy as np

x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [31]:
x[0]

1

In [32]:
x[-1]

5

In [33]:
x[-2]

4

In [34]:
# Modify the array

x[4] = 20 # update the element
x

array([ 1,  2,  3,  4, 20])

In [35]:
y = np.arange(1,10).reshape(3,3)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
y[0,0] # row 1 and column 1

1

In [37]:
y[1,2] # row 1 and column 2

6

In [38]:
np.delete(x, [0,2]) # Delete 1st and 3rd element from 1 D array

array([ 2,  4, 20])

In [39]:
np.delete(y , 0, axis=0) # Delete the first row from y


array([[4, 5, 6],
       [7, 8, 9]])

In [41]:
np.delete(y, 0, axis=1) # Delete the first column

array([[2, 3],
       [5, 6],
       [8, 9]])

In [42]:
np.delete(y, [0,2], axis = 1)

array([[2],
       [5],
       [8]])

In [43]:
# append the element
np.append(x , 8)


array([ 1,  2,  3,  4, 20,  8])

In [44]:
np.append(x , [7,6])

array([ 1,  2,  3,  4, 20,  7,  6])

In [48]:
np.append(y, [[4,7,6]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 7, 6]])

In [50]:
np.append(y, [[9], [10], [23]], axis = 1)

array([[ 1,  2,  3,  9],
       [ 4,  5,  6, 10],
       [ 7,  8,  9, 23]])